### ISSUE TITLE
GDIN test report clarification

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#108]
1. In the test report shared, can you please clarify the time window considered for calculating the CTR?  is this for entire duration of campaign or calculated on daily basis?

link for the rest report referred is :
https://github.com/Futurewei-io/blue-marlin/blob/master/Dataset_Analysis/GDIN_testing_report.pdf 
page 6

2. Can you please share the AUC data for your model training ?

**Comment by jimmylao** [comment]
1. The time window is the last 10 days in the dataset for CTR calculation. It is calculated for the whole testing period instead of daily basis.
2. the following is the log information while train one of the models
[None, 128]
[None, 128]
[None, 128]
[None, 128]
[None, 30, 128]
[None, 2]
test_gauc: 0.0000	 test_auc: 0.5000
Epoch 0 DONE	Global step: 206	Cost time: 95.04	train epoch average loss: 0.357736	train auc: 0.7612	test auc: 0.7695
Epoch 1 DONE	Global step: 412	Cost time: 188.78	train epoch average loss: 0.335080	train auc: 0.7727	test auc: 0.7804
Epoch 2 DONE	Global step: 618	Cost time: 283.22	train epoch average loss: 0.329516	train auc: 0.7793	test auc: 0.7749
Epoch 3 DONE	Global step: 824	Cost time: 378.69	train epoch average loss: 0.322138	train auc: 0.7919	test auc: 0.7921
Epoch 4 DONE	Global step: 1030	Cost time: 472.88	train epoch average loss: 0.314908	train auc: 0.8020	test auc: 0.7979
Epoch 5 DONE	Global step: 1236	Cost time: 566.90	train epoch average loss: 0.308221	train auc: 0.8154	test auc: 0.8086
Epoch 6 DONE	Global step: 1442	Cost time: 661.19	train epoch average loss: 0.303361	train auc: 0.8223	test auc: 0.8119
Epoch 7 DONE	Global step: 1648	Cost time: 756.26	train epoch average loss: 0.299187	train auc: 0.8274	test auc: 0.8154
Epoch 8 DONE	Global step: 1854	Cost time: 851.44	train epoch average loss: 0.295796	train auc: 0.8239	test auc: 0.7982
Epoch 9 DONE	Global step: 2060	Cost time: 945.56	train epoch average loss: 0.292872	train auc: 0.8270	test auc: 0.8112
Epoch 10 DONE	Global step: 2266	Cost time: 1039.72	train epoch average loss: 0.289356	train auc: 0.8385	test auc: 0.8046
Epoch 11 DONE	Global step: 2472	Cost time: 1134.98	train epoch average loss: 0.287715	train auc: 0.8449	test auc: 0.8185
Epoch 12 DONE	Global step: 2678	Cost time: 1229.32	train epoch average loss: 0.282767	train auc: 0.8437	test auc: 0.8183
Epoch 13 DONE	Global step: 2884	Cost time: 1324.89	train epoch average loss: 0.279613	train auc: 0.8491	test auc: 0.8051
Epoch 14 DONE	Global step: 3090	Cost time: 1417.43	train epoch average loss: 0.276848	train auc: 0.8530	test auc: 0.8160
Epoch 15 DONE	Global step: 3296	Cost time: 1508.31	train epoch average loss: 0.274020	train auc: 0.8575	test auc: 0.8212
Epoch 16 DONE	Global step: 3502	Cost time: 1598.19	train epoch average loss: 0.269496	train auc: 0.8615	test auc: 0.8250
Epoch 17 DONE	Global step: 3708	Cost time: 1690.19	train epoch average loss: 0.264787	train auc: 0.8517	test auc: 0.8082
Epoch 18 DONE	Global step: 3914	Cost time: 1780.91	train epoch average loss: 0.261616	train auc: 0.8520	test auc: 0.8079
Epoch 19 DONE	Global step: 4120	Cost time: 1871.79	train epoch average loss: 0.258637	train auc: 0.8680	test auc: 0.8167
Epoch 20 DONE	Global step: 4326	Cost time: 1962.86	train epoch average loss: 0.252366	train auc: 0.8779	test auc: 0.8067
Epoch 21 DONE	Global step: 4532	Cost time: 2053.77	train epoch average loss: 0.246949	train auc: 0.8740	test auc: 0.7663
Epoch 22 DONE	Global step: 4738	Cost time: 2144.14	train epoch average loss: 0.240136	train auc: 0.8789	test auc: 0.7891
Epoch 23 DONE	Global step: 4944	Cost time: 2234.01	train epoch average loss: 0.232930	train auc: 0.8733	test auc: 0.7831
Epoch 24 DONE	Global step: 5150	Cost time: 2325.38	train epoch average loss: 0.228404	train auc: 0.8951	test auc: 0.7454
Epoch 25 DONE	Global step: 5356	Cost time: 2415.59	train epoch average loss: 0.222541	train auc: 0.9026	test auc: 0.8040
Epoch 26 DONE	Global step: 5562	Cost time: 2505.37	train epoch average loss: 0.218246	train auc: 0.8620	test auc: 0.6957
Epoch 27 DONE	Global step: 5768	Cost time: 2595.54	train epoch average loss: 0.211224	train auc: 0.8816	test auc: 0.6916
Epoch 28 DONE	Global step: 5974	Cost time: 2686.71	train epoch average loss: 0.205137	train auc: 0.8452	test auc: 0.6919
Epoch 29 DONE	Global step: 6180	Cost time: 2776.18	train epoch average loss: 0.197469	train auc: 0.9068	test auc: 0.7512
best train_gauc 0.9068	test_gauc: 0.8250
