### ISSUE TITLE
Reg the environment 

### ISSUE THREAD

**Issue by zhentiwei** [Futurewei-io/blue-marlin#12]
To verify project, we try to build environment locally,  so we are going to purchase below graphics card .

But as per IT team, they are saying Ubuntu may don't have driver to support this higher end graphics card, 

So , could you please let's know which mode graphic card and which Ubuntu Version you are using? 

Nvidia Geforce RTX 2080 ti standard (Inno3D rtx 2080ti 11gb ddr6 twin fan (n208t3-11d6-1150va24)  

Thank you.

**Comment by jimmylao** [comment]
Here are the steps for setting up ubuntu OS with Nvidia graphics card
1. install Ubuntu OS
2. install driver for Nvidia card (in your case, driver for Geforce RTX 2080 ti). I think Nvidia has Ubuntu driver for this card (https://www.nvidia.com/download/driverResults.aspx/138279/). The power consumption of card is ~280w, you may need to double check the desktop that hosts this card has enough power to support this card
3. install CUDA toolkit
4. install CUDNN

To answer your question,
1. we are using 16.04 - since we installed Ubuntu quite a while ago, the version is kind of old
2. we have Nvida GPU card including: Tesla V100-DGXS with 32GB, Geforce Titan X Pascal with 12GB, Tesla k20 with 5GB, etc.
Ubuntu does not come with driver for these cards. The drivers are from Nvidia which are free to install

**Comment by zhentiwei** [comment]
OK, thanks for your detail clarification.
