### ISSUE TITLE
[look-alike-model] how to train look alike model on multiple GPUs

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#140]
I tried to train look alike model on 4 GPUs. But model is using single GPU . Would you  please suggest the code changes to train the model on multiple GPUs

![image](https://user-images.githubusercontent.com/8120966/110435257-d0d76380-80d8-11eb-9ccc-4059ab38f6e1.png)

**Comment by jimmylao** [comment]
Since normal training for lookalike model does not take long using single GPU (1 ~ 2 hours), the benefit in speedup while using multiple GPU may not be significant due to the load-balance between communication and parallelism. As it shows in the figure, you are using 40% of a single GPU's memory, you can simply enlarge batch size for speedup purposes.
