### ISSUE TITLE
Logs duration for DIN CTR predictor

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#152]
Hi,

As per our initial discussions, it will be sufficient to run the DIN algorithm for CTR predictor once in every 2 weeks. But, can you please clarify how much of logs ( showlog and clicklog) duration we should consider every 2 weeks to get best CTR prediction? 
in the config file you shared on git, you have used  almost 4 months of data. Isnt this too long considering the fact the user interests change frequently? Please suggest what can be the optimal number of days we can configure for this.

Dates referred in config.yml file are:

 'starting_date': '2019-12-19',
 'ending_date': '2020-04-15'

**Comment by jimmylao** [comment]
There are 2 parameters in the configuration of DIN algorithm

- the duration of logs (determined by 'starting_date' and 'ending_date')
- the length of sample (determined by 'length')

The purpose of the 1st parameter (duration of logs) is to provide a full picture of users' interests (multiple interests) with a relatively stable period of time. The length of each interest instance will be determined by the 2nd.

In order to capture full picture of users' interests, the log duration can not be too short, otherwise, the algorithm can only model partial interests. The purpose to train the model periodically (say, every 2 weeks) is to capture the change in users' interests under the assumption

- an old interest has more chance to be dropped from a user's interests list if the interest has not happened for a relatively longer time (log duration)
-  a newly developed interest can be captured by the model and the model needs to update accordingly

To balance the full picture of users' interests and computation burden, an optimal stable "log duration" is quite important, for example, 6~12 months.
