### ISSUE TITLE
DL Predictor clarification

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#156]
Hi,

While running DL predictions, we are facing an issue where the component code on model serving platform is giving error while reshaping the input timex .
The code that is giving error is:
self.timex1:np.reshape(timex, (1,60,63).
Error message is:
"ValueError('cannot reshape array of size 3300 into shape (1,60,63)',)".

When I checked the shape of timex, it is  (60, 55)  where as it should be (60, 63) as per our test environment and your code.
In this  shape of timex((60, 63)), I understand that 60 is the number of training days. Can you please clarify what is 63 in this shape?
Also, what  could have caused our predictor to send timex in the shape of (60, 55) instead of (60, 63) ?

**Comment by jimmylao** [comment]
@rangaswamymr 
timex includes a collection of features used in the model, total dimension adds up to 63. 

Here's a break-down of all features used in timex and their corresponding dimensions

| Feature       | dimension     | 
| :------------- | :----------: |
|  hits | 1   |
| dow   | 2 |
|  lagged| 2   |
| age| 7 |
| si| 37|
|network| 5|
|gender| 4|
|price_cat| 3|
|page_popularity| 1|
|quarter_autocorr| 1|
|**total**| **63**|

Please check dimension of each feature used in timex in predictor to understand why the total dimension add up to 55 instead of 63.
