### ISSUE TITLE
Less than one and negative values are appearing in Prediction

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#25]
**Less than one and negative values are appearing in Prediction**
We have train the module and generate 6 days prediction . we have observed almost all of the values are less then one and some are negative. Would Please suggest what is wrong i am doing in prediction code

I am sharing prediction results and python code with you

code:
[predictor.txt](https://github.com/Futurewei-io/blue-marlin/files/4267413/predictor.txt)

Results
[prediction_2020-01-26_TO_2020-01-31.txt](https://github.com/Futurewei-io/blue-marlin/files/4267422/prediction_2020-01-26_TO_2020-01-31.txt)

**Comment by zqlao** [comment]
Since you are using saved_model instead of ckpt_model for prediction, you need to define a convention (or signature) for input and output variables between saving and loading model steps.
In predictor.txt, input variables (pipe) are defined in session, while metagraphdef are defined in .pb file and loaded via tf.saved_model.loader.load, the code needs to define a convention between pipe and input/output variables in metagraphdef - signaturedef. Usually a signaturedef also needs to define when the model is saved in saved_model mode.
the code is messed up between ckpt and saved_model prediction process.
