### ISSUE TITLE
Some problems&feature request found in practical application of IMS2.0

### ISSUE THREAD

**Issue by Atlantis-s** [Futurewei-io/blue-marlin#40]
Hello everyone, we have actually applied IMS2.0 in projects for a while. In the process of application, we have identified the following problems and some feature requirements，we are very looking forward to communicate with you.
PS：My English is not very proficient, some expressions may not be very clear，so I used both English and Chinese to express，If you have any questions, welcome reply ：）
<br><br>
|  Number   | Description  | Urgency  | Importance  | Remarks  |
|  :----:  | ----  | :----:  | :----:  | ----  |
|  1  | Inventory estimation needs to consider the date attribute. For example, on weekdays, weekends, 618, Nov 11 carnival day, and holidays, the distribution of traffic is different.<br>(流量预估需要考虑日期属性，比如在工作日、周末、618、双11、节假日等日期流量的分布不同)  | P0  | P0  |   |
|  2  |Currently, the data source for inventory estimation is exposure data(SHOW_LOG), but some AD type are not suitable for using exposure data to estimate traffic, and using request data(REQ_LOG) is more objective.<br>(目前流量预估使用的是曝光数据，但是有些广告形式不太适宜使用曝光数据来预估流量，使用请求数据更客观)  | P0  | P0  |For example, because there is no historical show log data in the new ad slot, the estimated result will be 0, and we can not booking this ad slot. (Currently we added a force booking feature to evade this problem)<br>(比如，新上线广告位由于没有历史曝光数据，预估结果会为0，将导致无法锁量下单，当前我们新增了强制锁量的功能进行规避)|
|  3  |Performance issues: Currently, offline tasks run slower，such as the Predictor takes about 14 hours and the TBR takes about 10 hours. And offline tasks need to write a lot of data to the ES, which will affect the performance of online queries and so we cannot run it in the daytime. <br>(性能问题：离线任务耗时较长, 比如Predictor需要14小时，TBR需要10小时，且离线任务涉及到大量写ES，会影响在线查询的性能，不能放在白天跑)| P0  | P0  |Effect:<br>1.we need wait about 3 days to use a new audience package.<br>2.If the task run fails unfortunately, it needs to be rerun, which will takes a long time.<br>1.新打的人群包需要3天后才能询量;<br>2.如果由于任务失败需要重跑，则影响较大|
|  4  |Performance issues: It takes a long time to query ES during online inquiry. At present, a series of optimization measures have been used to optimize the time of one query from 10s to an average of 1.5s. However, multiple queries will be performed during a booking operating, and the cumulative query time will cost about 3s.<br>（性能问题：在线询量时查询ES耗时较长，目前已通过一系列优化措施将一次查询耗时由10s优化到平均1.5s，但是在一次锁量过程中会进行多次查询，累计查询耗时需要花费3s）| P1  | P1  |Current optimization measures:<br>1.Reduce the amount of ES data.(Forecast range reduced from 90 days to 30 days)<br>2.Reduce data accuracy.(Estimated result retains 2 decimal places)<br>3.Clean invalid data.(Data whose estimated result is 0 is not saved)<br>4.Merge ES data segments to reduce data fragmentation.<br>5.Store ES data in different index by date.<br>当前已采取的优化措施：<br>1.减少数据量（预测范围由90天减到了30天）<br>2.降低数据精度（预估结果保留2位小数）<br>3.清理无效数据（预估结果为0的数据不保存）<br>4.ES存储时合并分段，减少数据碎片<br>5.按日期分表存储|
|  5  |Consider frequency control factors in inventory estimation and booking.<br>（考虑频控因素的流量预估及分配）| P2  | P1  |   |
|  6  |If order A already purchased all the inventory under targeted condition X, when order B needs to buy the inventory under targeted condition Y which contain targeted condition X, then actually, the order B is allocated to the inventory that does not contain targeted condition X. when online advertise, if targeting condition X has remaining traffic, it cannot be delivered to order B.<br>（如果订单A已经购买了定向标签X下的全部库存流量，当接下来订单B需要购买包含定向X的定向Y下的流量时，实际上分配的是排除了定向X的那部分流量。这样当广告在线投放时，如果定向X还有剩余流量，也无法投放给订单B）| P2  | P2  |For schematic diagram please see below.|
|  7  |Currently, the TBR targeting condition are estimated by the overall ratio, which is a little inaccurate.<br>（当前tbr定向条件通过大盘比例来预估，准确性有待提升）| P3  | P2  |   |
|  8  |Consider smooth play scenes in booking.<br>（考虑匀速播放场景下的流量分配）| P3  | P2  |   |
|  9  |Hourly level inventory forecast and allocation.<br>（按小时级询量、锁量）| P3  | P3  |   |
|  10  |When the label is updated, the historical data don't refresh, which will affect the accuracy of the prediction.<br>（标签更新后，如果历史数据未能刷新，会影响预测的准确度）| P3  | P3  |For example, the residence location changed from Nanjing to Shenzhen.<br>比如常住地由南京更新为了深圳.|

<br><br>
### Problem 6 schematic diagram:
![image](https://user-images.githubusercontent.com/54946393/79867107-6231de80-8410-11ea-8939-269ee8233028.png)

**Comment by xun-hu-at-futurewei-com** [comment]
Number | Description | Urgency | Importance | Remarks | Solutions
-- | -- | -- | -- | -- | --
1 | Inventory   estimation needs to consider the date attribute. For example, on weekdays,   weekends, 618, Nov 11 carnival day, and holidays, the distribution of traffic   is different. | P0 | P0 |   | The current predicitor   is using Linear Reression to predict future CPM. This model does not have   enough data for special hodildays to predict. The new project which is   dl-predictor uses deep learning and is able to consider holidays and   weekdays.
(流量预估需要考虑日期属性，比如在工作日、周末、618、双11、节假日等日期流量的分布不同)
2 | Currently,   the data source for inventory estimation is exposure data(SHOW_LOG), but some   AD type are not suitable for using exposure data to estimate traffic, and   using request data(REQ_LOG) is more objective. | P0 | P0 | For   example, because there is no historical show log data in the new ad slot, the   estimated result will be 0, and we can not booking this ad slot. (Currently   we added a force booking feature to evade this problem) | ucdoc attributes are   traffic attribiues and they required to be define in such a way that their   values rarely change over time. The diffinication of si in this conext has to   be reviewed. Ad slot should indicate the categorical importantace of an ad   not an actual place holder.          We can not use any ad show log, we should use ad request log and make sure   that even without ad for this request, we still need to issue the ad request   for inventory purpose.          Another issue is that all ad request should be associated with trafiic and   should be stable.
(目前流量预估使用的是曝光数据，但是有些广告形式不太适宜使用曝光数据来预估流量，使用请求数据更客观) | (比如，新上线广告位由于没有历史曝光数据，预估结果会为0，将导致无法锁量下单，当前我们新增了强制锁量的功能进行规避)
3 | Performance   issues: Currently, offline tasks run slower，such as the Predictor takes about   14 hours and the TBR takes about 10 hours. And offline tasks need to write a   lot of data to the ES, which will affect the performance of online queries   and so we cannot run it in the daytime. | P0 | P0 | Effect: | The performance  of offline and online services depeneds on   the number of ucdocs and the number of predicted days. By reviewing the   values of ucdoc's attributes, we can achive less number of ucdocs and better   performance.           Based on the FACTDATA data, we found that UCKEY's region id is not correct.   The region id should be less than 80 based on original design. And the total   UCKEY should be around 10M instead of 100M, this will improve the performance   a lot.
(性能问题：离线任务耗时较长,   比如Predictor需要14小时，TBR需要10小时，且离线任务涉及到大量写ES，会影响在线查询的性能，不能放在白天跑) | 1.we need wait   about 3 days to use a new audience package.
  | 2.If the task   run fails unfortunately, it needs to be rerun, which will takes a long time.
  | 1.新打的人群包需要3天后才能询量;
  | 2.如果由于任务失败需要重跑，则影响较大
4 | Performance   issues: It takes a long time to query ES during online inquiry. At present, a   series of optimization measures have been used to optimize the time of one   query from 10s to an average of 1.5s. However, multiple queries will be   performed during a booking operating, and the cumulative query time will cost   about 3s. | P1 | P1 | Current   optimization measures: | The performance  of offline and online services depeneds on   the number of ucdocs and the number of predicted days. By reviewing the   values of ucdoc's attributes, we can achive less number of ucdocs and better   performance.           Based on the FACTDATA data, we found that UCKEY's region id is not correct.   The region id should be less than 80 based on original design. And the total   UCKEY should be around 10M instead of 100M, this will improve the performance   a lot. ES will be much faster.          We will post some analysis on Github.
（性能问题：在线询量时查询ES耗时较长，目前已通过一系列优化措施将一次查询耗时由10s优化到平均1.5s，但是在一次锁量过程中会进行多次查询，累计查询耗时需要花费3s） | 1.Reduce the   amount of ES data.(Forecast range reduced from 90 days to 30 days)
  | 2.Reduce data   accuracy.(Estimated result retains 2 decimal places)
  | 3.Clean invalid   data.(Data whose estimated result is 0 is not saved)
  | 4.Merge ES data   segments to reduce data fragmentation.
  | 5.Store ES data   in different index by date.
  | 当前已采取的优化措施：
  | 1.减少数据量（预测范围由90天减到了30天）
  | 2.降低数据精度（预估结果保留2位小数）
  | 3.清理无效数据（预估结果为0的数据不保存）
  | 4.ES存储时合并分段，减少数据碎片
  | 5.按日期分表存储
5 | Consider   frequency control factors in inventory estimation and booking. | P2 | P1 |   | There is a future plan   to look into this issue.
（考虑频控因素的流量预估及分配）
6 | If   order A already purchased all the inventory under targeted condition X, when   order B needs to buy the inventory under targeted condition Y which contain   targeted condition X, then actually, the order B is allocated to the   inventory that does not contain targeted condition X. when online advertise,   if targeting condition X has remaining traffic, it cannot be delivered to   order B. | P2 | P2 | For schematic diagram please see below. | This is current   design, all Y's traffic excludes X's traffic.. There is a future plan to look   into this issue.
（如果订单A已经购买了定向标签X下的全部库存流量，当接下来订单B需要购买包含定向X的定向Y下的流量时，实际上分配的是排除了定向X的那部分流量。这样当广告在线投放时，如果定向X还有剩余流量，也无法投放给订单B）
7 | Currently,   the TBR targeting condition are estimated by the overall ratio, which is a   little inaccurate. | P3 | P2 |   | There is a future plan   to look into this issue.
（当前tbr定向条件通过大盘比例来预估，准确性有待提升）
8 | Consider   smooth play scenes in booking. | P3 | P2 |   |  
（考虑匀速播放场景下的流量分配）
9 | Hourly   level inventory forecast and allocation. | P3 | P3 |   | There is a future plan   to look into this issue.
（按小时级询量、锁量）
10 | When   the label is updated, the historical data don't refresh, which will affect   the accuracy of the prediction. | P3 | P3 | For   example, the residence location changed from Nanjing to Shenzhen. | No, the offline   process is using existing Device table to join with log data to generate   FACTDATA table. We should be able to predict the future based on new FACTDATA   correctly.
（标签更新后，如果历史数据未能刷新，会影响预测的准确度） | 比如常住地由南京更新为了深圳.
