### ISSUE TITLE
Experimentation with Matrix Factorization to treat the sparse data 

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#46]
Our fact data facing data sparsity issue. I have experimented matrix factorization technique to treat the missing values .To implement matrix factorization algo, I have used Spark Alternative least square (ALS) API.I have used following steps 
( Reference : https://towardsdatascience.com/paper-summary-matrix-factorization-techniques-for-recommender-systems-82d1a7ace74)

Steps :
1.Prepare the fact data against uph key
Uph=uckey,pricing_cat,hour

![image](https://user-images.githubusercontent.com/8120966/84775518-f4afc200-affc-11ea-9859-f21bd4be017a.png)

2. Replaced these missing values with zero and normalize the time series data points values
![image](https://user-images.githubusercontent.com/8120966/84775542-fb3e3980-affc-11ea-8803-26e149433a3d.png)

3. Using Spark ALS API train the model and predict the results
![image](https://user-images.githubusercontent.com/8120966/84775566-02fdde00-affd-11ea-9e73-cf217b30024a.png)

![image](https://user-images.githubusercontent.com/8120966/84775575-05603800-affd-11ea-9bde-0b34139c9319.png)

![image](https://user-images.githubusercontent.com/8120966/84775587-098c5580-affd-11ea-87f7-654a11d8d456.png)

4. Final Time Series will be deformalized the values of ALS prediction
![image](https://user-images.githubusercontent.com/8120966/84775618-10b36380-affd-11ea-83db-595012d8145d.png)

Code :  
[als_sparse_data_treatment_after_normalization_py.txt](https://github.com/Futurewei-io/blue-marlin/files/4786725/als_sparse_data_treatment_after_normalization_py.txt)

Results:
[ALS_Results_csv.txt](https://github.com/Futurewei-io/blue-marlin/files/4786728/ALS_Results_csv.txt)

@jimmylao as par my understanding , matrix factorization does not change the data distribution.We can treat the missing values , without disturbing the pattern in time series. Please correct me if my finding is wrong

**Comment by jimmylao** [comment]
Thanks for sharing.
As indicated in the experimentation, matrix factorization can give you a good estimation of missing values in sparse data based on global data distribution. Since it's a global approximation approach, it also predicts non-missing values which may introduce errors (due to the nature of loss function defined in computing matrix factorization), we may need to balance benefit (missing value estimation) and cost (bias on existing true values, especially for the high sparse situation, there are cases where the count values are high, but very sparse in the time dimension) in using this approach to avoid introduced error passing on to subsequent prediction.
