### ISSUE TITLE
Experimentation with GradientBoostTreeRegression on very sparse data

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#47]
**Data Pre-processing :**

1.Select the data from 1-Nov-19 to 31-Jan-20
2.Select the sample of very sparse data (not suitable for deep learning) 
3.Divide day feature into 2 categorical variable
                  -Dow: day of week
                  -Dom: day of month

![image](https://user-images.githubusercontent.com/8120966/85037636-3ed2a800-b1a3-11ea-930a-c3d12ae99aa7.png)

4.Comma separated Uckey is divided into categorical variables ex. ads_type,slot_id…….

**GradientBoostTreeRegression:**
Our Deep learning model perform better in case of dense data (irrespective of linear/ non-linear nature of data)
Linear regression perform better when data is of linear nature
GradientBoostTreeRegression able to capture the non-linear nature of data 
I have trained the GradientBoostTreeRegression model and accuracy is better than LinearRgression 
RMS error is as follow

![image](https://user-images.githubusercontent.com/8120966/85038269-067f9980-b1a4-11ea-9c12-55d813d278b5.png)

**Prediction results:**
[gradient_boost_tree_regression_results_on_very_sparse_data_csv.txt](https://github.com/Futurewei-io/blue-marlin/files/4799428/gradient_boost_tree_regression_results_on_very_sparse_data_csv.txt)

**Futurework :** 
_1.To predict the traffic on country specific holydays, we can add holyday as a categorical variable 
2.We can train the RandomForestTreeRegression and compare the accuracy with existing models_

**Comment by jimmylao** [comment]
Thanks for sharing. The experiment result looks promising.

If I understand correctly, the idea is to cluster the data into clusters (dense, less-dense, less-sparse, sparse, for example), then building different models for different clusters based on their property. 

It's better to figure out:
1. How to cluster data into different clusters, especially boundary cases?
2. Will RandomForestTreeRegression work for other clusters, and will it turn out to be one model or multiple models in the final overall setting? Since sparse data's contribution to overall performance is kind of limited, the model is to predict traffic, major traffic may be more important than individual uckeys.

**Comment by asheeshiit** [comment]
RMS error of GradientBoostTree and RandomForestTree  regression 

![image](https://user-images.githubusercontent.com/8120966/85308068-62149480-b4ce-11ea-9470-7b2d86a14b33.png)


python code:
[gradient_boost_tree_regression_Spark_py.txt](https://github.com/Futurewei-io/blue-marlin/files/4814232/gradient_boost_tree_regression_Spark_py.txt)

[random_forest_Regression_Spark_py.txt](https://github.com/Futurewei-io/blue-marlin/files/4814237/random_forest_Regression_Spark_py.txt)
