### ISSUE TITLE
parameter calculation in config file

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#55]
I have few questions regarding the config parameters. For prediction as well as for training, there exists the following parameters:
cluster_size:      

1.       datapoints_min_th: 0.15
2.       datapoints_th_uckeys: 0.5
3.       datapoints_th_clusters: 0.5
4.       popularity_norm: 0.01
5.       popularity_th: 5
6.       median_popularity_of_dense: 1856.2833251953125

We would like to get access to the script which calculates the above mentioned parameters. Alternately, a document explaining how to calculate these parameters would also be helpful.

**Comment by jimmylao** [comment]
Assuming all data is in a 2D matrix of m x n (m rows and n columns), each row is a time-series signal.
Basically, there are 3 types of rows, i.e. 
1. bad row (will not be used)
2. sparse row (will be aggregated)
3. dense row (good)

1. Bad row
there are 2 criteria to determine if a row is a bad row, they are:
1). the row's popularity (mean value) < popularity_th (defined as 5)
2). the row's popularity > mean_popularity_of_dense (defined as 1856.2833251953125)
and
the row's percentage of non-zero columns < datapoints_min_th (defined as 0.15)
These 2 numbers are determined based on an analysis of the percentage of the sum of removed rows in total values of the matrix. 
According to our analysis, the 1) condition will remove ~400k rows whose total values contribute to only 0.12% of the matrix's total value; the 2) condition will remove 500~ rows whose total values contribute to only 0.52% of the matrix's total value. In other words, both conditions will add up to 0.64% of the matrix's total value which is trivial and will not affect the final result.

2. Sparse row
Once bad rows have been removed from the matrix, left-over rows will be marked as either dense row or sparse row. The criteria to mark if a row is a sparse row or not is as follows:

the row's normalized popularity < popularity_norm (defined as 0.01)
and
the row's percentage of non-zero columns < datapoints_th_uckeys (defined as 0.5)

there are 2 concepts need to be defined in order to understand the criteria above
popularity of row_i= mean value of row_i
normalied popularity of row_i = (popularity of row_i - mean of all rows' popularity) / std of all row's popularity
According to our analysis, the sum of all values in sparse row contributes to ~5% of the matrix's total value.

3. aggregate sparse rows into a virtual dense row (sparse rows cluster)
All sparse rows will be grouped into a few clusters, all sparse rows belong to a certain cluster will be aggregated and virtually be treated as a dense row.
After clustering, each virtual dense row will be dense in value, we still need to check whether they are dense in columns, the criteria to determine whether a virtual dense row is good or not is
the virtual dense row's percentage of non-zero columns > datapoints_th_clusters (defined as 0.5)

All the 3 steps mentioned above, all rows are either removed or dense enough and are ready for further processing.
