### ISSUE TITLE
How to increase the prediction window in DL

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#64]
@jimmylao I need your help to increase the prediction window in DL . As per my understanding ,in existing DL code we can increase  prediction window upto  14 day max .... 

My Findings are as follow :

DL Model set Training window  from params32 dictionary of hparams.py
File: from hparams.py
![image](https://user-images.githubusercontent.com/8120966/94238733-68cc0100-ff2e-11ea-8089-7498568e2563.png)

set prediction window  from config.yml
File: from config.yml
![image](https://user-images.githubusercontent.com/8120966/94239617-b6953900-ff2f-11ea-84c9-aa3b2064d204.png)

When we start Model Training .It check following condition (input_pipe.py)
File: input_pipe.py
 
![image](https://user-images.githubusercontent.com/8120966/94239566-a2513c00-ff2f-11ea-9f72-fb4d80bf6c19.png)

Where data_days=90(Maximum possible data point in time series)
From above condition we can infer the max possible value predict_window can take

**predict_window <((data_days-train_window))/2
predict_window <((90-60))/2
predict_window< 15
max(predict_window)=14**

Alternative solution: if we increase data_days .we can  increase the predict_window  . But the challenge is  to input more than 90 days data 

@jimmylao Can you please suggest any alternative approach ,So that we can increase the predict_window, without increasing the data_days ??

**Comment by jimmylao** [comment]
By default, the full dataset is split into 3 parts: training, testing, and validation. The number of days in testing and validation equal to predict_window. Due to the condition defined in input_pipe.py, if the full dataset is 90 days, the training dataset is 60 days, the maximum number of days of testing (prediction) is 14 days.
You can modify the assert defined in input_pipe.py to skip the reservation of the validation dataset as

asset inp.data_days > predict_window + train_window, "Predict+train window length is larger than the total number of days in dataset"

so that the maximum predict_window can be extended to 29.

**Comment by sanjaynirmal** [comment]
As per the current DL design we can forecast maximum 29 day impression  .But our business requirement is to preform prediction for 40 days
I would be thankful if you could suggest a better approach to handle requirement , otherwise we would stick to our solution 

Our solution : 
copy last 11 days forecasted impression and append 29 days prediction
example : if DL forecast the impression form 1-June to 29-june . we will copy 11 day prediction (from 20-june to 29-June ) and past against the date starting form 30-june to 10-july 

![issue_64](https://user-images.githubusercontent.com/40193781/98199155-94400380-1f50-11eb-89ff-19b2f44a1be1.png)

**Comment by asheeshiit** [comment]
Adding one more point .

**IMS require prediction on daily basis only (not on hourly basis)**

Processing day wise factdata will fix the time series sparsity issue up to some extend and improve model accuracy 
I would be thankful you could update these changes in DL ,otherwise we would stick to our solution 

**Our Approach: prediction on daily basis = sum (prediction on hourly basis)**

**Comment by jimmylao** [comment]
@sanjaynirmal 
The DL model can meet the 40-day requirement.  
The default total period of days is 90 days, the 90 days will cover both training and testing, i.e. training + testing = 90 days. If training = 60 days (default), the maximum testing days is 30 days. 
If the total period of days is 120 days and training is 70 days, the maximum testing days will be 120 - 70 = 50 days.

@asheeshiit 
The prediction from the DL model is daily basis. 
The current pipeline will distribute the daily basis prediction to hourly basis prediction based on some pre-calculated distribution (hourly percentage). If daily basis prediction instead of hourly basis prediction is preferred, the daily basis -> hourly basis distribution step in the pipeline needs to be skipped.
