### ISSUE TITLE
Performance statistics ??

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#8]
**Would you please share following performance statistics**
Q1. How many concurrent request per second can be handled by the current model??

Q2. Would you please share the model latency(time taken by the saved model to produce the result) Vs concurrent request per second graph??

Q3. Would you please share the Precision , Recall and Accuracy  values of current model??

Q4. What are the limitations and area of improvement of current model??

**Comment by jimmylao** [comment]
Q1: we encourage user to test it him/herself with real-world data
Q2: please refer to Q1
Q3: since this is not a classification model, precision/recall/accuracy are not used to evaluate the performance of model. MAPE (mean absolute percentage error) is used to measure the difference between predicted value vs prediction ground truth (https://en.wikipedia.org/wiki/Mean_absolute_percentage_error)
Q4: quarterly correlation and page_popularity features are defined, but not used. these features can potentially help improve the performance of the model via using real world data.
