### ISSUE TITLE
DIN code compatibility with python3

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#90]
The current DIN model runs on python2.7 which could be an issue for running it on some production environments which have only python3 as default. Can we check the compatibility of this code with python3.6+

**Comment by jimmylao** [comment]
Please refer to issue [#89](https://github.com/Futurewei-io/blue-marlin/issues/89) for the running environment of DIN model, it does support Python 3.6 and has been verified. Please make sure our released code instead of the original DIN code.

Please keep me posted if there's any problem running DIN under python3.6
