### ISSUE TITLE
[DIN] Any solution to process the user data directly from TFRecord ?

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#98]
We receive around 400-500GB user impression data per day (show log) and 50-60GB user Click data (click log) per day. If we want to process 30days data, data size will be around 15TB. 
As I go through the code, I found that we are performing model training using data in pickle format

![image](https://user-images.githubusercontent.com/8120966/103272551-2e697880-49e3-11eb-94a7-cd03f5297383.png)

I doubtful, if we can run DIN model

**Can blue-marlin team please provide any solution which can read data directly from TFRecord ??**

**Comment by jimmylao** [comment]
The "dataset.pkl" as well as "label.pkl" in "train.py" were generated by "gdin_build_dataset.py".
The input data for "gdin_build_dataset.py" is in the format of TFRecord (generated from spark).
In order to read data directly from TFRecord, you can modify (or generate a new function) the "run" function in "gdin_build_dataset.py" as follows:

1. remove the lines (186 ~ 194) of saving data to pickle files ("dataset.pkl" and "label.pkl")
2. return those variables (used to be saved to pickle files)

then in "train.py", 

1. import the newly defined function from "gdin_build_dataset.py"
2. replace the lines reading pickle files via calling the newly defined function in "gdin_build_dataset.py"

BTW, although the raw showlog data is huge, the information passed to "dataset.pkl" is at a much much smaller scale as compared to raw data.

**Comment by xunh** [comment]
The real dataset read every time is just a bucket of the whole dataset. The huge size dataset will only slow down the process.Sent from my Huawei phone-------- Original message --------From: jimmylao <notifications@github.com>Date: Tue, Dec 29, 2020, 08:33To: Futurewei-io/blue-marlin <blue-marlin@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [Futurewei-io/blue-marlin] [DIN] Any solution to process the user data directly from TFRecord ? (#98)
The "dataset.pkl" as well as "label.pkl" in "train.py" were generated by "gdin_build_dataset.py".
The input data for "gdin_build_dataset.py" is in the format of TFRecord (generated from spark).
In order to read data directly from TFRecord, you can modify (or generate a new function) the "run" function in "gdin_build_dataset.py" as follows:
remove the lines (186 ~ 194) of saving data to pickle files ("dataset.pkl" and "label.pkl")return those variables (used to be saved to pickle files)
then in "train.py",
import the newly defined function from "gdin_build_dataset.py"replace the lines reading pickle files via calling the newly defined function in "gdin_build_dataset.py"
BTW, although the raw showlog data is huge, the information passed to "dataset.pkl" is at a much much smaller scale as compared to raw data.

**Comment by radibnia77** [comment]
Data of TFRecors is aggregated. It is not as huge as log data and having it as pickle file seems just fine. What is the size of tfrecords?
